version: '3.8'

services:
  dbga:
    image: postgres
    restart: always
    ports:
      - "32000:5432"
    env_file:
      - ./process.env
    networks:
      - grandes_aromas_net
    container_name: dbga

  haproxy:
    build: ./haproxy
    depends_on:
      - dbga
      - auth_micro
      - users_micro
      - store_micro
      - ui_micro1
      - ui_micro2
    container_name: haproxy
    ports:
      - "5080:80"
    networks:
      - grandes_aromas_net

  ui_micro1:
    build: ./ui/.
    container_name: ui_micro1
    command: npm start
    depends_on:
      - dbga
      - auth_micro
      - users_micro
      - store_micro
    networks:
      - grandes_aromas_net
  
  ui_micro2:
    build: ./ui/.
    container_name: ui_micro2
    command: npm start
    depends_on:
      - dbga
      - auth_micro
      - users_micro
      - store_micro
      - ui_micro1
    networks:
      - grandes_aromas_net

  users_micro:
    build: ./users/.
    container_name: users_micro
    command: npm start
    ports:
      - "3001:3001"
    depends_on:
      - dbga
    env_file:
      - ./process.env
    volumes:
      - ./config:/var/www/html/config
    networks:
      - grandes_aromas_net

  store_micro:
    build: ./store/.
    container_name: store_micro
    command: npm start
    ports:
      - "3002:3002"
    depends_on:
      - dbga
    env_file:
      - ./process.env
    volumes:
      - ./config:/var/www/html/config
    networks:
      - grandes_aromas_net

  auth_micro:
    build: ./auth/.
    container_name: auth_micro
    command: npm start
    ports:
      - "3003:3003"
    depends_on:
      - dbga
    env_file:
      - ./process.env
    volumes:
      - ./config:/var/www/html/config
    networks:
      - grandes_aromas_net

networks:
  grandes_aromas_net:
